version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: rbmgmt
      POSTGRES_USER: rbuser
      POSTGRES_PASSWORD: rbpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rbmgmt
      SPRING_DATASOURCE_USERNAME: rbuser
      SPRING_DATASOURCE_PASSWORD: rbpass
      JWT_SECRET: ${JWT_SECRET:-devsecretdevsecretdevsecretdevsec}
      CORS_ALLOWED_ORIGINS: http://localhost:5173,http://localhost
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8080/api
    environment:
      VITE_API_URL: http://localhost:8080/api
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:


