ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE;
UPDATE users SET email = CONCAT(username, '@example.local') WHERE email IS NULL;
ALTER TABLE users ALTER COLUMN email SET NOT NULL;

-- Seed admin user with pre-hashed password (BCrypt for 'admin123')
-- Hash below generated by BCryptPasswordEncoder(10)
INSERT INTO users (username, email, password)
VALUES ('admin', 'admin@example.com', '$2a$10$N9qo8uLOickgx2ZMRZo5e.7p8YjZLxQkZ4fU6Y4ZC/7gv2Fne5DEy')
ON CONFLICT (username) DO NOTHING;

-- Assign ADMIN role to admin user
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE u.username = 'admin' AND r.name = 'ADMIN'
ON CONFLICT DO NOTHING;


